# For details, see the GoReleaser documentation at http://goreleaser.com
project_name: synse-client-go
before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - format: tar.gz
checksum:
  name_template: 'checksums-{{ .Tag }}.txt'
release:
  github:
    owner: vapor-ware
    name: synse-client-go
  draft: false
  prerelease: auto
  name_template: "{{ .Version }}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'