version: 3
devices:
  - type: led
    metadata:
      model: emul8-led
    instances:
      - info: Synse LED
        tags:
          - foo/bar
        alias:
          name: emulator-led
        data:
          id: 1
