#
# server.yml
#
# Runs Synse Server and its Emulator Plugin configured to communicate over TCP.
# This is used for integration testing.
#

version: '3'
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:latest
    ports:
    - '5000:5000'
    links:
    - emulator
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator:5001

  emulator:
    container_name: emulator
    image: vaporio/emulator-plugin:latest
    expose:
    - '5001'
    command: ['--debug']
    volumes:
    - ./config:/tmp/config
    - ./config/device:/tmp/device
    environment:
      PLUGIN_CONFIG: /tmp/config
      PLUGIN_DEVICE_CONFIG: /tmp/device
